name: GlobalVillagerDiscounts
version: ${project.version}
main: dev.murqin.globaldiscounts.GlobalVillagerDiscounts
api-version: '1.21'
author: murqin
description: Synchronizes villager trade discounts across all players on the server.
website: https://github.com/murqin/GlobalVillagerDiscounts

commands:
  gvd:
    description: GlobalVillagerDiscounts commands
    usage: /gvd <info|toggle|clear|clearall|disable|enable>

permissions:
  gvd.admin:
    description: Allows use of admin commands (clear, clearall, disable, enable)
    default: op
